- name: nopcommerce
  become: yes
  hosts: all
  tasks:
    - name: Initial system update
      include_tasks: updatesystem.yml

    - name: install required files
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
        - unzip
        - wget
        - curl
        - mysql-server

    - name: Enable and start the nginx and mysql service
      systemd_service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - nginx
        - mysql

    - name: download the required .net files
      get_url:
        url: "https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb"
        dest: /tmp/packages-microsoft-prod.deb

    - name: Install the downloaded Microsoft packages
      apt:
        deb: /tmp/packages-microsoft-prod.deb
        state: present

    - name: Update system after adding Microsoft repository
      include_tasks: updatesystem.yml

    - name: Install .NET SDK
      apt:
        name: "{{item}}"
        state: present
      loop:
        - aspnetcore-runtime-8.0
        - dotnet-sdk-8.0
    - name: Set MySQL root password
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: "RootStrongPass!"
        login_unix_socket: /var/run/mysqld/mysqld.sock
    - name: Remove anonymous MySQL users
      community.mysql.mysql_user:
        name: ""
        host_all: yes
        state: absent
        login_user: root
        login_password: "RootStrongPass!"
    - name: Remove test database
      community.mysql.mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "RootStrongPass!"
    - name: Restrict root login to localhost
      community.mysql.mysql_user:
        name: root
        host: "%"
        state: absent
        login_user: root
        login_password: "RootStrongPass!"
    - name: Create nopCommerce database
      community.mysql.mysql_db:
        name: nopcommerce
        state: present
        login_user: root
        login_password: "RootStrongPass!"
    - name: Create nopCommerce DB user
      community.mysql.mysql_user:
        name: nopuser
        password: "StrongPassword123!"
        priv: "nopcommerce.*:ALL"
        host: localhost
        state: present
        login_user: root
        login_password: "RootStrongPass!"
