---
- name: k8s
  become: yes
  hosts: all
  tasks:
    - name: System Update
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: Copy the files
      ansible.builtin.copy:
        dest: /etc/modules-load.d/containerd.conf
        content: |
          overlay
          br_netfilter
        owner: root
        group: root
        mode: "0644"
