- name: install tomcat
  become: yes
  hosts: all
  vars:
    - username: tomcat
    - home_dir: /opt/tomcat
    - default_shell: /bin/false
    - tomcat_version: 9.0.60
    - tomcat_latest: /opt/tomcat/latest
    - tomcat_bin_directory: /opt/tomcat/bin
  tasks:
    - name: Update apt repo and update_cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install openjdk 11
      package:
        name: "{{java_package}}"
        state: present
    - name: Create tomcat user
      user:
        home: "{{home_dir}}"
        shell: "{{default_shell}}"
        name: "{{username}}"
    - name: Download tomcat
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.60/bin/apache-tomcat-9.0.60.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
    - name: Unarchive the artifacts
      unarchive:
        src: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
        dest: "{{ home_dir }}"
        creates: "{{ home_dir }}/apache-tomcat-{{ tomcat_version }}"
        group: "{{username}}"
        owner: "{{username}}"
        remote_src: true
    - name: Change ownership
      file:
        path: "{{home_dir}}"
        state: directory
        recurse: true
        group: "{{username}}"
        owner: "{{username}}"
    - name: find all the .sh files in the tomcat bin directory
      ansible.builtin.find:
        paths: "{{ tomcat_bin_directory }}"
        patterns: "*.sh"
      register: sh_files_tomcat_bin
    - name: print the files from the previous
      debug:
        var: sh_files_tomcat_bin
