- name: install tomcat
  become: yes
  hosts: all
  vars:
    - username: tomcat
    - home_dir: /opt/tomcat
    - default_shell: /bin/false
    - tomcat_version: 9.0.60
    - tomcat_latest: /opt/tomcat/apache-tomcat-9.0.60
    - tomcat_admin_user: devops
    - tomcat_admin_password: devops
    - tomcat_users_relative: conf/tomcat-users.xml
  tasks:
    - name: Update apt repo and update_cache
      ansible.builtin.apt:
        update_cache: yes
    - name: Install openjdk 11
      package:
        name: "{{java_package}}"
        state: present
    - name: Create tomcat user
      user:
        home: "{{home_dir}}"
        shell: "{{default_shell}}"
        name: "{{username}}"
    - name: Download tomcat
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.60/bin/apache-tomcat-9.0.60.tar.gz"
        dest: "/tmp/apache-tomcat-{{ tomcat_version }}.tar.gz"
    - name: Unarchive the artifacts
      unarchive:
        src: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
        dest: "{{ home_dir }}"
        creates: "{{ home_dir }}/apache-tomcat-{{ tomcat_version }}"
        group: "{{username}}"
        owner: "{{username}}"
        remote_src: true
    - name: Change ownership
      file:
        path: "{{home_dir}}"
        state: directory
        recurse: true
        group: "{{username}}"
        owner: "{{username}}"
    - name: find all the .sh files in the tomcat bin directory
      ansible.builtin.find:
        paths: /opt/tomcat/apache-tomcat-{{tomcat_version}}/bin
        patterns: "*.sh"
      register: sh_files_tomcat_bin
    - name: print the files from the previous
      debug:
        var: sh_files_tomcat_bin
    - name: Make shell script executable
      file:
        path: "{{item.path}}"
        owner: "{{username}}"
        group: "{{username}}"
        mode: "0755"
      loop: "{{sh_files_tomcat_bin.files}}"
    - name: copy the service file
      template:
        src: "tomcat.service.j2"
        dest: /etc/systemd/system/tomcat.service
        owner: "{{username}}"
        group: "{{username}}"
    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      meta: flush_handlers
    - name: Reload the daemon and start the tomcat service
      systemd_service:
        name: "tomcat.service"
        daemon_reload: true
        enabled: yes
        state: started
    - name: create a tomcat users file
      template:
        src: "tomcat-users.xml.j2"
        dest: "{{ tomcat_latest }}/{{ tomcat_users_relative }}"
        owner: "{{username}}"
        group: "{{username}}"
      notify:
        - reload the daemon, enable and start the tomcat service
  handlers:
    - name: reload the daemon, enable and start the tomcat service
      systemd_service:
        name: "tomcat.service"
        daemon_reload: yes
        enabled: yes
        state: restarted
